## Artificial Intelligence Assignment 2
## No2. Error Backpropagation 1
## 20132651 Sungjae Lee

In [1]:
import numpy as np
np.random.seed(0)

In [2]:
N, D = 3, 4

In [3]:
x = np.random.randn(N, D)
y = np.random.randn(N, D)
z = np.random.randn(N, D)

In [4]:
a = x * y
b = a + z
c = np.sum(b)

In [5]:
## (1) 해당 연산망의 그래프 연산을 손으로 작성

In [11]:
grad_c = 1.0
grad_b = grad_c * np.ones((N, D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x
print(grad_c, grad_b, grad_a)
print(grad_z, grad_x, grad_y)

1.0 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]] [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


In [ ]:
## (2) grad_c ~ grad_y 출력 확인

In [20]:
import torch
x = torch.randn(N, D, requires_grad = True)
y = torch.randn(N, D, requires_grad = True)
z = torch.randn(N, D)

In [22]:
a = x * y
b = a + z
c = torch.sum(b)

In [23]:
c.backward()

In [25]:
print(grad_x)
print(grad_y)

[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
