## Artificial Intelligence Assignment 2
## No11. DMLP (4) ReLU 함수 사용의 경우
## 20132651 Sungjae Lee

In [1]:
import numpy as np
def ReLU(mat):
    if mat < 0:
        return np.matrix('0')
    else:
        return mat

In [2]:
x = np.matrix('1.0 0.0')
bias = np.matrix('1.0')
print(bias, x)

[[1.]] [[1. 0.]]


In [3]:
x0 = np.concatenate((bias, x), axis = 1)

In [4]:
u1_1 = np.matrix('-0.3 1.0 1.2').transpose()
u1_2 = np.matrix('1.6 -1.0 -1.1').transpose()

In [5]:
x1_1 = np.matmul(x0, u1_1)
x1_2 = np.matmul(x0, u1_2)
print(x1_1, x1_2)

[[0.7]] [[0.6]]


In [6]:
x1 = np.concatenate((bias, ReLU(x1_1), ReLU(x1_2)), axis = 1)
print(x1)

[[1.  0.7 0.6]]


In [7]:
u2_1 = np.matrix('1.0 1.0 -1.0').transpose()
u2_2 = np.matrix('0.7 0.5 1.0').transpose()

In [8]:
x2_1 = np.matmul(x1, u2_1)
x2_2 = np.matmul(x1, u2_2)
print(x2_1, x2_2)

[[1.1]] [[1.65]]


In [9]:
x2 = np.concatenate((bias, ReLU(x2_1), ReLU(x2_2)), axis = 1)
print(x2)

[[1.   1.1  1.65]]


In [10]:
u3_1 = np.matrix('0.5 -0.8 0.9').transpose()
u3_2 = np.matrix('-0.1 0.3 0.4').transpose()

In [11]:
x3_1 = np.matmul(x2, u3_1)
x3_2 = np.matmul(x2, u3_2)
print(x3_1, x3_2)

[[1.105]] [[0.89]]


In [12]:
x3 = np.concatenate((bias, ReLU(x3_1), ReLU(x3_2)), axis = 1)
print(x3)

[[1.    1.105 0.89 ]]


In [13]:
u4_1 = np.matrix('1.0 0.1 -0.2').transpose()
u4_2 = np.matrix('-0.2 1.3 -0.4').transpose()

In [14]:
x4_1 = np.matmul(x3, u4_1)
x4_2 = np.matmul(x3, u4_2)
print(x4_1, x4_2)

[[0.9325]] [[0.8805]]


In [15]:
o = np.concatenate((ReLU(x4_1), ReLU(x4_2)))

In [16]:
print(0.949, 1.095)
print(o)

0.949 1.095
[[0.9325]
 [0.8805]]
